/***************************************************************************
Name : ResponseHandler
Created By : Aditya Chasta
Created Date : 06/13/2017
Description : Response Handler class handle response received on accessing API
***************************************************************************/
global virtual class F8_WebResponseHandler {
    //List of custom attributes that we want to check the status of the org
    
}